<?php

use Illuminate\Database\Seeder;

class InstituteTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // reset the users table
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('institutes')->truncate();
        // generate 3 users
        DB::table('institutes')->insert([
            ['name' => 'Ahsania Mission University of Science and Technology (Academic programs have not yet started)',],
            ['name' => 'Ahsanullah University of Science and Technology',],
            ['name' => 'American International University-Bangladesh',],
            ['name' => 'Anwer Khan Modern University',],
            ['name' => 'Army University of Engineering and Technology (BAUET) Qadirabad',],
            ['name' => 'ASA University Bangladesh',],
            ['name' => 'Asian University of Bangladesh',],
            ['name' => 'Atish Dipankar University of Science and Technology',],
            ['name' => 'Bandarban University (Academic programs have not yet started)',],
            ['name' => 'Bangabandhu Sheikh Mujib Medical University',],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Agricultural University',],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Digital University',],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Maritime University',],
            ['name' => 'Bangabandhu Sheikh Mujibur Rahman Science and Technology University',],
            ['name' => 'Bangamata Sheikh Fojilatunnesa Mujib Science and Technology University',],
            ['name' => 'Bangladesh Agricultural University',],
            ['name' => 'Bangladesh Army International University of Science and Technology(BAIUST) Comilla',],
            ['name' => 'Bangladesh Army University of Science and Technology(BAUST) Saidpur',],
            ['name' => 'Bangladesh Islami University',],
            ['name' => 'Bangladesh Open University',],
            ['name' => 'Bangladesh University',],
            ['name' => 'Bangladesh University of Business and Technology',],
            ['name' => 'Bangladesh University of Engineering and Technology',],
            ['name' => 'Bangladesh University of Health Sciences',],
            ['name' => 'Bangladesh University of Professionals',],
            ['name' => 'Bangladesh University of Textiles',],
            ['name' => 'Barisal University',],
            ['name' => 'Begum Rokeya University',],
            ['name' => 'BGC Trust University Bangladesh',],
            ['name' => 'BGMEA University of Fashion and Technology(BUFT)',],
            ['name' => 'BRAC University',],
            ['name' => 'Britannia University',],
            ['name' => 'Canadian University of Bangladesh',],
            ['name' => 'CCN University of Science and Technology',],
            ['name' => 'Central University of Science and Technology',],
            ['name' => "Central Women's University",],
            ['name' => 'Chittagong Independent University',],
            ['name' => 'Chittagong Medical University',],
            ['name' => 'Chittagong University of Engineering and Technology',],
            ['name' => 'Chittagong Veterinary and Animal Sciences University',],
            ['name' => 'City University',],
            ['name' => 'Comilla University',],
            ['name' => "Cox's Bazar International University",],
            ['name' => 'Daffodil International University',],
            ['name' => 'Dhaka International University',],
            ['name' => 'Dhaka University of Engineering and Technology',],
            ['name' => 'East Delta University',],
            ['name' => 'East West University',],
            ['name' => 'Eastern University',],
            ['name' => 'European University of Bangladesh',],
            ['name' => 'Exim Bank Agricultural University Bangladesh',],
            ['name' => 'Fareast International University',],
            ['name' => 'Feni University',],
            ['name' => 'First Capital University of Bangladesh',],
            ['name' => 'German University Bangladesh',],
            ['name' => 'Global University Bangladesh',],
            ['name' => 'Gono Bishwabidyalay',],
            ['name' => 'Green University of Bangladesh',],
            ['name' => 'Hajee Mohammad Danesh Science and Technology University',],
            ['name' => 'Hamdard University Bangladesh',],
            ['name' => 'IBAIS University',],
            ['name' => 'Independent University Bangladesh',],
            ['name' => 'International Islamic University Chittagong',],
            ['name' => 'International Standard University (Academic programs have not yet started)',],
            ['name' => 'International University of Business Agriculture and Technology',],
            ['name' => 'Ishakha International University Bangladesh',],
            ['name' => 'Islamic Arabic University',],
            ['name' => 'Islamic University',],
            ['name' => 'Jagannath University',],
            ['name' => 'Jahangirnagar University',],
            ['name' => 'Jatiya Kabi Kazi Nazrul Islam University',],
            ['name' => 'Jessore University of Science and Technology',],
            ['name' => 'Khulna Khan Bahadur Ahsanullah University (Academic programs have not yet started)',],
            ['name' => 'Khulna University',],
            ['name' => 'Khulna University of Engineering and Technology',],
            ['name' => 'Khwaja Yunus Ali University',],
            ['name' => 'Leading University',],
            ['name' => 'Manarat International University',],
            ['name' => 'Mawlana Bhashani Science and Technology University',],
            ['name' => 'Metropolitan University',],
            ['name' => 'N.P.I University of Bangladesh',],
            ['name' => 'National University',],
            ['name' => 'Noakhali Science and Technology University',],
            ['name' => 'North Bengal International University',],
            ['name' => 'North East University Bangladesh',],
            ['name' => 'North South University',],
            ['name' => 'North Western University',],
            ['name' => 'Northern University Bangladesh',],
            ['name' => 'Northern University of Business and Technology Khulna',],
            ['name' => 'Notre Dame University Bangladesh',],
            ['name' => 'Pabna University of Science and Technology',],
            ['name' => 'Patuakhali Science And Technology University',],
            ['name' => 'Port City International University',],
            ['name' => 'Premier University',],
            ['name' => 'Presidency University',],
            ['name' => 'Prime University',],
            ['name' => 'Primeasia University',],
            ['name' => 'Pundra University of Science and Technology',],
            ['name' => 'Queens University',],
            ['name' => 'Rabindra Maitree University Kushtia',],
            ['name' => 'Rabindra University Bangladesh',],
            ['name' => 'Rajshahi Medical University',],
            ['name' => 'Rajshahi Science and Technology University (RSTU) Natore',],
            ['name' => 'Rajshahi University of Engineering and Technology',],
            ['name' => 'Ranada Prasad Shaha University',],
            ['name' => 'Rangamati Science and Technology University',],
            ['name' => 'Royal University of Dhaka',],
            ['name' => 'Rupayan A.K.M Shamsuzzoha University (Academic programs have not yet started)',],
            ['name' => 'Shah Makhdum Management University Rajshahi (Academic programs have not yet started)',],
            ['name' => 'Shahjalal University of Science and Technology',],
            ['name' => 'Shanto-Mariam University of Creative Technology',],
            ['name' => 'Sheikh Fazilatunnesa Mujib University',],
            ['name' => 'Sheikh Hasina University',],
            ['name' => 'Sher-e-Bangla Agricultural University',],
            ['name' => 'Sonargaon University',],
            ['name' => 'Southeast University',],
            ['name' => 'Southern University Bangladesh',],
            ['name' => 'Stamford University Bangladesh',],
            ['name' => 'State University of Bangladesh',],
            ['name' => 'Sylhet Agricultural University',],
            ['name' => 'Sylhet International University',],
            ['name' => 'Tagore University of Creative Arts Keranigonj Bangladesh (Academic programs have not yet started)',],
            ['name' => 'The International University of Scholars',],
            ['name' => 'The Millennium University',],
            ['name' => "The People's University of Bangladesh",],
            ['name' => 'The University of Asia Pacific',],
            ['name' => 'The University of Comilla',],
            ['name' => 'Times University Bangladesh',],
            ['name' => 'Trust University Barishal (Academic programs have not yet started)',],
            ['name' => 'United International University',],
            ['name' => 'University of Chittagong',],
            ['name' => 'University of Creative Technology Chittagong',],
            ['name' => 'University of Development Alternative',],
            ['name' => 'University of Dhaka',],
            ['name' => 'University of Global Village',],
            ['name' => 'University of Information Technology and Sciences',],
            ['name' => 'University of Liberal Arts Bangladesh',],
            ['name' => 'University of Rajshahi',],
            ['name' => 'University of Science and Technology Chittagong',],
            ['name' => 'University of South Asia',],
            ['name' => 'Uttara University',],
            ['name' => 'Varendra University',],
            ['name' => 'Victoria University of Bangladesh',],
            ['name' => 'World University of Bangladesh',],
            ['name' => 'Z.H Sikder University of Science and Technology',],
            ['name' => 'Z.N.R.F. University of Management Sciences',],
        ]);
    }
}
