@extends('layouts.container')


@section('content')
    <div class="kt-content  kt-grid__item kt-grid__item--fluid" id="kt_content">
        <div class="row">
            

            


            <div class="col-sm-12">
                <!--begin::Portlet-->
                <div class="kt-portlet">
                    <div class="kt-portlet__head">
                        <div class="kt-portlet__head-label">
                            <h3 class="kt-portlet__head-title">
                               {{ Carbon\Carbon::parse($year.'-'.$month)->format('M Y') }} - Hold Employee List
                            </h3>
                        </div>
                    </div>
                    <div class="kt-portlet__body">

                        <div class="kt-section">
                            <div class="kt-section__content">
                                <table class="table table-bordered table-hover">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Employee</th>
                                        <th>Department</th>
                                        <th>Process-Segment</th>
                                        <th>Gross Salary</th>
                                        <th>Payable Salary</th>
                                        <th>Salary Generated By</th>
                                        <th>Salary Generated At</th>
                                        <th>Actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($salaryHistory as $row)
                                        <tr>
                                            <th scope="row">{{ $loop->iteration }}</th>

                                            <td>
                                                {{ $row->employee->employer_id }}- {{ $row->employee->FullName }}
                                            </td>
                                            <td>
                                                 @foreach($row->employee->departmentProcess->unique('department_id') as $item)
                                                    {{ $item->department->name ?? null }}@if(!$loop->last && $item->department) , @endif
                                                @endforeach                                       
                                            </td>
                                            <td>
                                                @foreach($row->employee->departmentProcess->unique('department_id') as $item)
                                                    {{ $item->process->name ?? null }}@if(!$loop->last && $item->process) , @endif
                                                @endforeach
                                                -
                                                @foreach($row->employee->departmentProcess->unique('department_id') as $item)
                                                {{ $item->processSegment->name ?? null }}@if(!$loop->last && $item->processSegment) , @endif
                                                @endforeach

                                            </td>
                                            <td>{{ $row->gross_salary }}</td>
                                            <td>{{ $row->payable_amount }}</td>
                                            <td>{{ $row->createdBy->FullName }}</td>
                                            <td>{{ Carbon\Carbon::parse($row->created_at)->format('d M, Y') }}</td>
                                            <td>
                                                <button title="Release Hold Salary for {{ Carbon\Carbon::parse($year.'-'.$month)->format('M Y') }}" data-toggle="modal" data-target="#kt_modal" action="{{ route('salary.hold.release', ['id'=>$row->id]) }}" class="btn text-primary custom-btn globalModal"><i class="fa fa-plug" aria-hidden="true"></i></button>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
                <!--end::Portlet-->

            </div>
        </div>
    </div>



    


    
@endsection


@push('css')
    {{--    <link href="{{ asset('assets/vendors/general/bootstrap-select/dist/css/bootstrap-select.css') }}" rel="stylesheet" type="text/css"/>--}}
    <link href="{{ asset('assets/vendors/general/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css') }}" rel="stylesheet" type="text/css"/>
@endpush

@push('library-js')
    <script src="{{ asset('assets/vendors/general/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}" type="text/javascript"></script>
@endpush

@push('js')
    {{-- <script src="{{ asset('assets/js/demo1/pages/crud/forms/widgets/dropzone.js') }}" type="text/javascript"></script> --}}
    <script src="{{ asset('assets/vendors/general/bootstrap-select/dist/js/bootstrap-select.js') }}"
            type="text/javascript"></script>

    <script src="{{ asset('assets/js/demo1/pages/crud/forms/widgets/select2.js') }}" type="text/javascript"></script>

    <script>
        $('#editBankModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var recipient = button.data('bankid');
            var modal = $(this);
            var url = '{{route('get.bank', ['id' => ':recipient'])}}';
            url = url.replace(':recipient', recipient);

            axios.get(url)
                .then(function (response) {
                    console.log(response.data.bank_name);
                    modal.find('#bank-id').val(response.data.id);
                    modal.find('#edit-bank-name').val(response.data.bank_name);
                })
                .catch(function (error) {
                    // handle error
                    console.log(error);
                    modal.find('.modal-form')[0].reset();
                })
        });
    </script>

    <script>
        $('#editBranchModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var recipient = button.data('branchid');
            var modal = $(this);
            var url = '{{route('get.branchByBranchId', ['id' => ':recipient'])}}';
            url = url.replace(':recipient', recipient);
            console.log(url)
            axios.get(url)
                .then(function (response) {
                    console.log(response.data)
                    modal.find('#branch-id').val(response.data.id);
                    modal.find('#edit-branch-name').val(response.data.bank_branch_name);
                    modal.find('#edit-bank-routing').val(response.data.bank_routing);
                })
                .catch(function (error) {
                    // handle error
                    console.log(error);
                    modal.find('.modal-form')[0].reset();
                })
        });


         
         function myFunction(val) {
            let payableAmount  = parseInt($('#originalPayableAmount').val());
            let amount = parseInt(val);
            if(amount > payableAmount){
                $('#amount').val('');
                $('#payableAmount').html(payableAmount)
            }
            else{
                $('#amount').val(val);
            }

            var remain = payableAmount - amount;
            $('#payableAmount').html(remain);
        }

            
    </script>

@endpush
